### PR TITLE
Customization work from reinteractive.

### PR DESCRIPTION
**Pull request by GlenCrawford**
Customization work from reinteractive.

(Likely still a few more things to add during the remainder of the day).

### CODE REVIEW

**Comment by rtrvrtg** [comment]
Hi Glen,
Thanks for sending that through. I'm using a `develop` branch forked from the current upstream master and it looks like there's a few conflicts to resolve. I might take a look at these and see how extensive they are.
-geoffrey

**Comment by GlenCrawford** [comment]
Yeah, I need to take a look at that on my end, too. Looks like the NYPL people added some new things to their `master` branch since we started.

**Comment by rtrvrtg** [comment]
I did a test merge on my local, and got the following list of conflicting files.

```text
README.md
public/assets/css/app.css
public/assets/js/admin.min.js
public/assets/js/default.min.js
public/assets/js/templates.js
```

I might leave you to handle the merge from their master - let me know if you have any questions.

**Comment by GlenCrawford** [comment]
Okay, so I've updated the reinteractive fork's `develop` branch with the latest from NYPL's `master` branch: eb37f08..724b9ec.

That means that the last couple of weeks of changes that NYPL have made to their codebase had to be pulled into our code. That *shouldn't* be a problem, but there's always the chance that anything that they've done recently might break some of our CSS or features or something. I'll deploy the branch to staging soon, and I'm sure that if anything is broken by the updates, it'll be noticable in Jenna's testing.

**Comment by rtrvrtg** [comment]
@GlenCrawford Have you been able to get your new `develop` branch up on the staging instance? I'm afraid that I haven't had the chance to review it yet - things have been a bit hectic today.

**Comment by GlenCrawford** [comment]
Hey @rtrvrtg, yep, it's all up on staging:

```
Branch develop (at edb8f85d45cb7aab44a82c0d59c8d7b376ee7e8a) deployed as release 20160619171100 by glen
```

**Pull request merged**
